---
apiVersion: v1
kind: Service
metadata:
  name: openldap
spec:
  selector:
    app.kubernetes.io/name: openldap
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
  type: ClusterIP