apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.5.0
        ports:
        - containerPort: 389
        env:
        - name: KEEP_EXISTING_CONFIG
          value: "true"
        - name: LDAP_TLS
          value: "false"
        volumeMounts:
        - name: data
          mountPath: /var/lib/ldap
          subPath: database
        - name: data
          mountPath: /etc/ldap/slapd.d
          subPath: config
        - name: data
          mountPath: /vol
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: openldap-data