apiVersion: batch/v1
kind: Job
metadata:
  name: openldap-preparation
spec:
  template:
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.5.0
        args: ["--skip-process-files"]
        ports:
        - containerPort: 389
        envFrom:
          - configMapRef:
              name: openldap-config
        volumeMounts:
        - name: data
          mountPath: /var/lib/ldap
          subPath: database
        - name: data
          mountPath: /etc/ldap/slapd.d
          subPath: config
        - name: data
          mountPath: /vol
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: openldap-data
      restartPolicy: Never