---
- name: Install a cronjob to auto refresh ecr token
  hosts: all
  remote_user: admin
  become: yes

  tasks:
  - name: Creates the ~/.aws directory
    ansible.builtin.file:
      path: /root/.aws
      state: directory

  - name: Creates the ~/.docker directory
    ansible.builtin.file:
      path: /root/.aws
      state: directory

  - name: Set AWS credentials
    ansible.builtin.template:
      src: res/aws-credentials.j2
      dest: /root/.aws/credentials

  - name: Set ECR helper config
    ansible.builtin.template:
      src: res/docker-config.json.j2
      dest: /root/.docker/config.json

  - name: Creates the registries.yaml
    ansible.builtin.file:
      path: /root/.aws
      state: directory

  - name: Set ECR helper config
    ansible.builtin.template:
      src: res/k3s-registries.yaml
      dest: /etc/rancher/k3s/registries.yaml
