---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  labels:
    app.kubernetes.io/name: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgadmin4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgadmin4
    spec:
      containers:
      - name: pgadmin4
        image: biarms/pgadmin4:4.21
        ports:
          - name: http
            containerPort: 5050
