---
apiVersion: batch/v1
kind: Job
metadata:
  name: pin-syncthing-data
spec:
  template:
    spec:
      containers:
      - name: hello
        image: hello-world
        imagePullPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: syncthing-data
      nodeSelector:
        kubernetes.io/hostname: dewberry
      restartPolicy: Never