---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi